server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8050 # 连接你刚搭好的控制台
        port: 8719 # 通信端口，冲突自动+1
      eager: true # 立即初始化
    gateway:
      server:
        webflux:
          # 自动从Nacos发现服务
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true # 必须加，解决大小写问题

          # 路由规则（完全不变，只是层级变了）
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/user/**

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/order/**

    # Nacos 注册中心配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
